name: auth_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.3.3
  flutter_easyloading: ^3.0.5
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.3
  network_info_plus: ^6.1.4
  network_tools: ^5.0.2
  ping_discover_network_forked: ^0.0.1
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.4
  intl: ^0.19.0
  curved_navigation_bar: ^1.0.6
  internet_connection_checker: ^3.0.1
  internet_connection_checker_plus: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#04Bc2c"
  image: assets/images/splash/spp.png
  android_12:
    image: assets/images/splash/spp.png
    icon_background_color: "#04Bc2c"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash/sp.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#04Bc2c"